version: '2'

services:
  
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    ports:
      - "3000:80"

  ros-master:
    build: 
      context: .
      dockerfile: dockerfile
    image: aprendendo_ros2:latest

  terminal:
    image: aprendendo_ros2:latest
    ipc: host
    depends_on:
      - xserver
      - ros-master
    volumes_from:
      - xserver
      - ros-master
    volumes:
      - ./src:/home/robot/ws_aprendendo_ros2/src:rw
    environment:  
      - ROS_MASTER_URI=:http://ros-master:11311    
      - DISPLAY=:9
    command:
      - /bin/bash
      - -c
      - |
        # xterm -hold -T Terminal -e "tmux" 
        # xterm -hold -T Terminal -e "ros2 launch pacote_de_exemplos display.launch.py" 
        # xterm -hold -T Terminal -e "ros2 launch pacote_de_exemplos load.launch.py" 
        # xterm -hold -T Terminal -e "ros2 launch pacote_de_exemplos mapping_slam_toolbox.launch.py" 
        # xterm -hold -T Terminal -e "ros2 launch pacote_de_exemplos mapping_cartographer.launch.py" 
        xterm -hold -T Terminal -e "ros2 launch pacote_de_exemplos navigation.launch.py" 
