version: '2'

services:
  
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    ports:
      - "3000:80"

  ros-master:
    build: 
      context: .
      dockerfile: dockerfile
    image: aprendendo_ros2:latest
    ipc: host
    security_opt:
      - seccomp:unconfined
    depends_on:
      - xserver
    volumes_from:
      - xserver
    environment:
      - DISPLAY=:9

  terminal:
    image: aprendendo_ros2:latest
    depends_on:
      - ros-master
    volumes_from:
      - ros-master
    volumes:
      - .:/home/robot/ws_aprendendo_ros2:rw
    environment:  
      - ROS_MASTER_URI=:http://ros-master:11311    
      - DISPLAY=:9
    command:
      - /bin/bash
      - -c
      - |
        xterm -hold -T Terminal -e "tmux" 


  simulador:
    image: aprendendo_ros2:latest
    ipc: host
    security_opt:
      - seccomp:unconfined
    depends_on:
      - ros-master
    volumes_from:
      - ros-master
    environment:  
      - ROS_MASTER_URI=:http://ros-master:11311    
      - DISPLAY=:9
    privileged: true
    command:
      - /bin/bash
      - -c
      - |
        xterm -hold -T Simulator -e "ros2 launch gazebo_ros gazebo.launch.py" 
