version: '2'

services:
  
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    ports:
      - "3000:80"

  ros-master:
    build: 
      context: .
      dockerfile: dockerfile
    image: aprendendo_ros2:latest
    ipc: host
    security_opt:
      - seccomp:unconfined
    depends_on:
      - xserver
    volumes_from:
      - xserver
    environment:
      - DISPLAY=:9
    # command:
    #   - /bin/bash
    #   - -c
    #   - |
    #     source /opt/ros/humble/setup.bash && source /home/robot/ws_aprendendo_ros2/install/setup.bash && xacro /home/robot/ws_aprendendo_ros2/install/hera_description/share/hera_description/robots/hera_full.urdf.xacro -o /home/robot/ws_aprendendo_ros2/install/hera_description/share/hera_description/robots/hera_full.urdf
        
  terminal:
    image: aprendendo_ros2:latest
    depends_on:
      - ros-master
    volumes_from:
      - ros-master
    volumes:
      - ./src:/home/robot/ws_aprendendo_ros2/src:rw
    environment:  
      - ROS_MASTER_URI=:http://ros-master:11311    
      - DISPLAY=:9
      # - TURTLEBOT3_MODEL=burger
      # - LDS_MODEL=LDS-01
    command:
      - /bin/bash
      - -c
      - |
        xterm -hold -T Terminal -e "tmux" 


  simulador:
    image: aprendendo_ros2:latest
    ipc: host
    security_opt:
      - seccomp:unconfined
    depends_on:
      - ros-master
    volumes_from:
      - ros-master
    environment:  
      - ROS_MASTER_URI=:http://ros-master:11311    
      - DISPLAY=:9
      - GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/usr/share/gazebo-11/models/:/home/robot/gazebo_models
    privileged: true
    command:
      - /bin/bash
      - -c
      - | 
        xterm -hold -T Simulator -e "ros2 launch gazebo_ros gazebo.launch.py" 


  hera:
    image: aprendendo_ros2:latest
    ipc: host
    security_opt:
      - seccomp:unconfined
    depends_on:
      - ros-master
    volumes_from:
      - ros-master
    volumes:
      - ./src:/home/robot/ws_aprendendo_ros2/src:rw
    environment:  
      - ROS_MASTER_URI=:http://ros-master:11311    
      - DISPLAY=:9
      - GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/usr/share/gazebo-11/models/:/home/robot/gazebo_models
    privileged: true
    command:
      - /bin/bash
      - -c
      - | 
        xterm -hold -T Hera -e "source install/setup.bash && ros2 launch hera_description load_description.launch.py" 
